<robot name="cubo" xmlns:xacro="http://www.ros.org/wiki/xacro">


	<xacro:property name="PI" value="3.1415926535897931"/>

	<xacro:property name="chassisHeight" value="0.1"/>
	<xacro:property name="chassisLength" value="0.4"/>
	<xacro:property name="chassisWidth" value="0.2"/>
	<xacro:property name="chassisMass" value="50"/>

	<xacro:property name="casterRadius" value="0.05"/>
	<xacro:property name="casterMass" value="5"/>

	<xacro:property name="wheelWidth" value="0.05"/>
	<xacro:property name="wheelRadius" value="0.1"/>
	<xacro:property name="wheelPos" value="0.2"/>
	<xacro:property name="wheelMass" value="5"/>

	<xacro:property name="cameraSize" value="0.05"/>
	<xacro:property name="cameraMass" value="0.1"/>

	<xacro:include filename="$(find mybot_description)/urdf_2/mybot.gazebo" />
	 <xacro:include filename="$(find mybot_description)/urdf_2/materials.xacro" />
	 <xacro:include filename="$(find mybot_description)/urdf_2/macros.xacro" />


	<link name="footprint" />


	<joint name="base_joint" type="fixed">
	  <parent link="footprint"/>
	  <child link="chassis"/>
	</joint>

	<link name='chassis'>
	  <collision> 
	    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
	    <geometry> 
	      <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
	    </geometry> 
	  </collision>
	  <visual> 
	    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
	    <geometry> 
	      <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
	    </geometry> 
	    <material name="orange"/>
	  </visual>
	 <inertial> 
	    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
	    <mass value="${chassisMass}"/> 
	    <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
	  </inertial>
	</link>


  	<link name="camera">
	  <collision>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
	    </geometry>
	  </collision>

	  <visual>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
	    </geometry>
	    <material name="red"/>
	  </visual>

	  <inertial>
	  	<origin xyz="0 0 0" rpy="0 0 0"/>
	    <mass value="${cameraMass}" />
	    <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
	  </inertial>
	</link>
        <joint name="base_camera" type="fixed">
	  <origin xyz="0 0 ${chassisHeight*2}" rpy="0 0 0"/>
	  <parent link="chassis"/>
	  <child link="camera"/>
	</joint>


		




</robot>
